### PR TITLE
Replace variable in header and footer support

### LINKED ISSUE #34: Replace variable in header and footer
Is it possible to replace the variables in header and footer, I tried your example but only replace the variables in the content but not header and footer.

### PR DESCRIPTION
**Pull request by youngyou**
Fixes #34

### CODE REVIEW

**Comment by shakthifuture** [comment]
@youngyou , You have fixed header and footer issue? how to test this?

**Comment by youngyou** [comment]
> @youngyou , You have fixed header and footer issue? how to test this?
I'll add some test.

**Comment by shakthifuture** [comment]
Can I test? what maven version we have to use for get header and footer fix? I need this fix very urgent.

**Comment by youngyou** [comment]
> Can I test? what maven version we have to use for get header and footer fix? I need this fix very urgent.

Just use it same as before.  And variables in header and footer will be replaced.

**Comment by shakthifuture** [comment]
Maven not downloaded latest jar's. So i cannot test and result also failed. I am using the below maven dependency.
                <dependency>
			<groupId>pl.jsolve</groupId>
			<artifactId>templ4docx</artifactId>
			<version>2.0.2</version>
		</dependency>

**Comment by youngyou** [comment]
> Maven not downloaded latest jar's. So i cannot test and test also failed. I am using the below maven dependency.
> 
> pl.jsolve
> templ4docx
> 2.0.2

The changes hadn't synced to maven repo now.
You may use [Jitpack](https://jitpack.io) or some other methods to load this lib form GitHub.

**Comment by shakthifuture** [comment]
It not worked, could you please sync to maven repo?

**Comment by youngyou** [comment]
> It not worked, could you please sync to maven repo?

Sorry. It's not maintained by me. Ask @lstypka .
By the way, I'm adding supports for more features.

**Comment by shakthifuture** [comment]
ok thank you for you work..  @lstypka , is possible sync the repo to maven?

**Comment by youngyou** [comment]
> ok thank you for you work.. @lstypka , is possible sync the repo to maven?

A new PR created. And you can simply download the code to you project if necessary.

**Comment by fjloma** [comment]
+1
 @lstypka please, update maven repo

**Comment by youngyou** [comment]
> +1
> @lstypka please, update maven repo

Try my fork and check the readme.

**Pull request merged**
